### ISSUE TITLE
Add support for exceptions

### ISSUE THREAD

**Issue by xwipeoutx** [Wedvich/structured-log-seq-sink#3]
`structured-log` puts exceptions in the `LogEvent`'s `error` field.  This should be pushed to Seq's `Exception` field. 

See http://docs.getseq.net/docs/posting-raw-events

**Comment by Wedvich** [comment]
@xwipeoutx It does this already if using `structured-log >= 0.1.0` with the latest version of this sink (`0.3.3`). Isn't this working for you?

**Comment by xwipeoutx** [comment]
I'm running latest of each (just pulled them today), and I had a quick squiz at the source before raising it.

It works with the console sink - see the JS error stack trace displays
![image](https://cloud.githubusercontent.com/assets/1008567/22413406/37fccc54-e703-11e6-959f-d1dc23fda0a7.png)

But not in the Seq sink
![image](https://cloud.githubusercontent.com/assets/1008567/22413426/67262598-e703-11e6-9995-67f18eeaec86.png)

I believe the payload to Seq needs to include an `Exception` property (`@x` in compact mode)

**Comment by xwipeoutx** [comment]
Ah sorry @Wedvich, I was running from `master` not from `HEAD` - the 0.3.3 tag isn't in the master branch!

**Comment by Wedvich** [comment]
Oh shit, you're right! I'll get that sorted out, apologies!

30. jan. 2017 15:46 skrev "Steve Leigh" <notifications@github.com>:

**Comment by Wedvich** [comment]
I have no idea how it happened, but it looks like the tagged commit got orphaned somehow, and I don't have the original branch anywhere. It was more or less impossible to retrieve from GitHub to connect it back to master. Since the tagged commit was still here though, I just created a new commit (https://github.com/Wedvich/structured-log-seq-sink/commit/d288595ef01a5aeca116b744eb53eb6965428acd) from the same source files and moved the v0.3.3 tag up to that, so you should be able to find it in master now. Sorry for the mess!

**Comment by xwipeoutx** [comment]
That works I guess. FWIW, next you can switch to the master branch and just merge the commit (which was cf4ef56efb8934ec2f72fa6cb195b2df941b6030 ) into `master` with fast-forward. That would just move the master branch up to that commit.

**Comment by Wedvich** [comment]
Yep, I was trying to that, but I couldn't fetch that commit to my local repo from GitHub in any way - not by tag, or the commit hash itself. I have no idea why, and I wasn't really in the mood to fight with Git 😄
